# vim:syntax=dockerfile
#------------------------------------------------------------------------------
# Dockerfile for building and testing Solidity AFL fuzzers on CI
# Target: Ubuntu AFL Clang variant
#
# solidity-fuzzing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# solidity-fuzzing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with solidity-fuzzing.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2026 solidity-fuzzing contributors.
#------------------------------------------------------------------------------
FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        ccache \
        clang \
        cmake \
        git \
        libboost-all-dev \
        lld \
        llvm \
        llvm-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 -b v0.26.8 https://github.com/tree-sitter/tree-sitter /tmp/tree-sitter \
    && test "$(git -C /tmp/tree-sitter rev-parse HEAD)" = "cd5b087cd9f45ca6d93ab1954f6b7c8534f324d2" \
    && make -C /tmp/tree-sitter -j"$(nproc)" install \
    && ldconfig \
    && rm -rf /tmp/tree-sitter
