name: Build Fuzz

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-fuzz:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ossfuzz:latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Build fuzzers
        run: scripts/build_ossfuzz.sh
